CREATE TABLE users (
  userid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(50) NOT NULL,
  pwd varchar(250) NOT NULL,
  email VARCHAR(250)
);

CREATE TYPE priority as ENUM (
    'High',
    'Med',
    'Low'
);

CREATE TABLE incidents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50),
    comments VARCHAR(255),
    users_id INTEGER
        REFERENCES users(userid) ON DELETE CASCADE NOT NULL,
    inc_pri priority,
    office_location VARCHAR(50)
);

CREATE TYPE roles as ENUM (
    'Admin',
    'Tech',
    'Other'
);

CREATE TYPE states AS ENUM (
    'AL',
    'AK',
    'AR',
    'AZ',
    'CA',
    'CO',
    'CT',
    'DC',
    'DE',
    'FL',
    'GA',
    'HI',
    'IA',
    'ID',
    'IL',
    'IN',
    'KS',
    'KY',
    'LA',
    'MA',
    'MD',
    'ME',
    'MI',
    'MN',
    'MO',
    'MS',
    'MT',
    'NC',
    'ND',
    'NE',
    'NH',
    'NJ',
    'NM',
    'NV',
    'NY',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VA',
    'VT',
    'WA',
    'WI',
    'WV',
    'WY'
);


CREATE TABLE employees (
  emp_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fname varchar(50) NOT NULL,
  lname varchar(50) NOT NULL,
  email VARCHAR(250),
  emp_address VARCHAR(100),
  emp_st states NOT NULL,
  emp_zip VARCHAR(5),
  office_location VARCHAR(100),
  emp_roles roles NOT NULL 
);