DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS incidents CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP ROLE IF EXISTS roles;
DROP ROLE IF EXISTS states;
DROP ROLE IF EXISTS priority;