CREATE TYPE priority as ENUM (
    'High',
    'MED',
    'Low',
);

CREATE TABLE incidents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(50),
    comments VARCHAR(255),
    users_id INTEGER
        REFERENCES users(userid) ON DELETE CASCADE NOT NULL,
    inc_pri priority,
    Office_location VARCHAR(50),
);

